# Default values for fleet-poc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

hpaEnabled: true

minReplicaCount: 2
maxReplicaCount: 15

targetCPUUtilizationPercentage: 80

image:
  repository: gabrielbiasi/rancher-fleet-poc
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 30051

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
