apiVersion: v1
kind: Service
metadata:
  name: {{ include "fleet-poc.fullname" . }}
  labels:
    {{- include "fleet-poc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: {{ .Values.service.port }}
  selector:
    {{- include "fleet-poc.selectorLabels" . | nindent 4 }}
